### ISSUE TITLE
Long required arguments issue

### ISSUE THREAD

**Issue by VSirunyan** [jamolnng/argparse#2]
Program doesn't correctly understand arguments that have long version, try to give required argument with two versions, for example: parser.add("-l", "--long", "long required argument", true);

Problem is "if" in line 120: "if (_variables.find(a._name) == _variables.end())".

Change condition to "_variables.find(a._name) == _variables.end()
              && _variables.find(_pairs.find(a._name)->second) == _variables.end()"

**Comment by jamolnng** [comment]
https://github.com/jamolnng/argparse/pull/3
