### ISSUE TITLE
Check for both short and long flags

### ISSUE THREAD

**Issue by DraTeots** [jamolnng/argparse#6]
Hi! Thanks for the lib. I really enjoy that it is small and flexible. 

I have something, that I would think as a bug. But maybe it is unintuitive feature? 

Code: 
```c++
parser.add_argument("-v", "--verbose", "Description", false);

// ... 
if(parser.exists("v")) {     // or parser.get<bool>("v")
    // ...
}
```

When I run 
``` bash

program -v=2   # works!
program --verbose=2  # Don't work and parser.exists("v") == false
```

**Comment by jamolnng** [comment]
currently this library does not use the equals sign to assign values to arguments, it just uses white space. So to achieve what you are trying to do you would want to type this

`program -v 2` or `program --verbose 2`

To explain what, this is what is going on with your current way
`program -v=2` works because when there is only one `-` it treats every character as if the program was given 
`program -v -= -2`

However when there are two dashes `--verbose=2` it treats the whole thing as one so if
`parser.exists("verbose=2")` would return true

**Comment by DraTeots** [comment]
Aha! Thanks for the clarification! 

Are there plans to make `--long=something`? 
(I could, actually, look into that if that is on the list)

**Comment by jamolnng** [comment]
I hadn't really thought of it until you opened this issue. The main problem I see is how to handle list arguments such as `program -v 1 2 3 4`

**Comment by DraTeots** [comment]
Now if you do `getv<int>` you get a vector with [1,2,3,4]. Right? 

I would say, that if a user writes 

```
program --verbose=1 2 3 4
# or even
program -v=1 2 3 4
```

Awaited result should be: `-v=1` and 2,3,4 are free arguments. It is kind of... one gets used to it on unix systems - spaces mean another arguments. To fix it one awaits something like ```program --verbose="1 2 3 4"``` if you do ```--verbose``` and want spaces between `1 2 3 4`. In this particular case a natural behaviour from argparse would be not to split values automatically but just to keep it as a string. 

Going back to the beginning. I would say, that having ```program -v 1 2 3 4``` might be very convenient (while a bit unusual for me). But `=` introduces the **strict intention** `program --verbose=1 2 3 4` means `--verbose=1`

BTW, for my app I would like to have a behaviour like
```sh
program               # program produces some output
program --verbose     # set verbosity to debug
program --verbose=0   # disable any output
program --verbose=off # same as --verbose=0
program --verbose input-file.txt   # set verbosity to debug, and PROCESS input-file.txt
```
That is my actual problem now =)

**Comment by DraTeots** [comment]
Any thoughts on this?

**Comment by jamolnng** [comment]
I do think single value options with `=` are a good idea. vectors still seem weird. I'm gonna move this discussion to it's own issue
