### ISSUE TITLE
dependency on std::experimental::filesystem

### ISSUE THREAD

**Issue by astibal** [jamolnng/argparse#8]
Hi,
what is the plan with `std::experimental::filesystem` dependency? There is only `_bin` variable declared, and unused.

Regards,
Ales

**Comment by jamolnng** [comment]
It is used [here](https://github.com/jamolnng/argparse/blob/develop/argparse.h#L289) but I agree it that for some it could be an unnecessary dependency. I'll see if I can think of any alternatives.

**Comment by pgp** [comment]
I guess the purpose of that line is extracting a path from the executable filename (and the working directory, presumably).. I would suggest not to do this at all, since argv[0] can be crafted to contain anything..

**Comment by jamolnng** [comment]
It is true that argv[0] can theoretically have any value but on most systems it is crafted to have the filename of the program being run.

See:
https://www.gnu.org/software/libc/manual/html_node/Program-Arguments.html
or
https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=vs-2019

**Comment by pgp** [comment]
You're right, but not relying on argv[0] for the program name is more a security concern than a convenience one. By the way, as far as I known, std::experimental::filesystem is not available on all toolchains, and even worse, the dependency changes to std::filesystem if one wants to use C++17...

**Comment by jamolnng** [comment]
fair, if the dependency were to be removed then I think argv[0] should just be ignored

**Comment by jamolnng** [comment]
removed dependency https://github.com/jamolnng/argparse/commit/07e771d64e66ff32c72b0949c07d5116378705dd
